cmake_minimum_required(VERSION 3.10)
project(physics_sim)
set(CMAKE_OSX_ARCHITECTURES "arm64")
find_package(raylib QUIET)
set(SOURCE_FILES vec2.cpp vec3.cpp physics_solver2d.cpp physics_solver3d.cpp simulator2d.cpp simulator3d.cpp main.cpp)
set(CMAKE_CXX_COMPILER /usr/bin/g++)
set(CMAKE_GENERATOR "Make")
add_executable(${PROJECT_NAME} ${SOURCE_FILES})
target_link_libraries(${PROJECT_NAME} raylib)
if (APPLE)
    target_link_libraries(${PROJECT_NAME} "-framework IOKit")
    target_link_libraries(${PROJECT_NAME} "-framework Cocoa")
    target_link_libraries(${PROJECT_NAME} "-framework OpenGL")
endif()